### ISSUE TITLE
The error was: 'dict object' has no attribute 'ansible_facts'

### ISSUE THREAD

**Issue by patsevanton** [stephane-klein/ansible-role-sentry#10]
**Describe the bug**
The error was: 'dict object' has no attribute 'ansible_facts'

Playbook
```
---
- hosts: sentry
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: install pip3
      apt: name=python3-pip state=present
    - name: Install multi python packages with version specifiers
      pip:
        name:
          - docker
          - docker-compose
  roles:
    - role: geerlingguy.docker
    - role: ansible-role-sentry

```

Inventory
```
all:
  children:
    sentry:
      hosts:
        "sentry":
          ansible_host: "xxxx"
  vars:
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
```

error:
```
TASK [ansible-role-sentry : Write SENTRY_SECRET_KEY to /srv/sentry/sentry_secret_key] ************************************************************************
Thursday 07 April 2022  14:34:55 +0600 (0:01:10.080)       0:03:48.445 ********
fatal: [sentry]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_facts'

    The error appears to be in '/home/user/.ansible/roles/ansible-role-sentry/tasks/install.yml': line 38, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


    - name: Write SENTRY_SECRET_KEY to {{ sentry_project_path }}/sentry_secret_key
      ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:

        with_items:
          - {{ foo }}

    Should be written as:

        with_items:
          - "{{ foo }}"
```

Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```
